// Please do not edit this file!

export type UserRole = "Client" | "Vendor"

export type ItemStatus = "Draft" | "Active" | "Sold"

export type OrderStatus = "Shipped" | "Delivered"

export interface User {
  firstName: string;
  lastName: string;
  email: string;
  profileImg: string;
  role: UserRole;
  cart?: string[];
}

export interface Item {
  title: string;
	price: number;
	desc: string;
	category: string;
	img: string;
	vendorID: string;
	status: ItemStatus;
}

export interface Order {
	itemID: string;
	clientID: string;
	vendorID: string;
	status: OrderStatus;
}