// Please do not edit this file!

export type UserRole = "Client" | "Vendor";

export type ItemStatus = "Draft" | "Active" | "Carted" | "Sold";

export type OrderStatus = "Shipped" | "Delivered";

export interface ItemDate {
  day: number;
  month: string;
  year: number;
}

export interface User {
  firstName: string;
  lastName: string;
  email: string;
  desc: string;
  profileImg: string;
  role: UserRole;
  cart?: string[];
}

export interface Item {
  title: string;
  price: number;
  desc: string;
  date?: ItemDate;
  category: string;
  img: string;
  vendorID: string;
  status: ItemStatus;
  id: string;
  cartedBy?: string | null;
}

export interface Order {
  itemID: string;
  clientID: string;
  vendorID: string;
  status: OrderStatus;
}

export interface AuthContextType {
  currentUser: User | null;
  loading: boolean;
}

export interface ProfileInfo {
  name: string;
  role: UserRole;
  desc: string;
  img: string;
}

export interface Tabs {
  tab1: string;
  tab2: string;
  tab3: string;
}
