// Please do not edit this file!!!

export type UserRole = "Client" | "Vendor"

export interface ItemDate {
  day: number;
  month: string;
  year: number;
}

export interface Item {
  title: string;
  price: number;
  date: ItemDate;
  img: string;
  role: UserRole;
  category: string;
}

export interface ProfileInfo {
  name: string;
  role: UserRole;
  desc: string;
  img: string;   
}


export interface Tabs {
  tab1: string
  tab2: string
  tab3: string
}